FROM golang:1.20.6 as build

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
RUN CGO_ENABLED=1 make build

FROM debian:12.0 as main

COPY --from=build /app/app /
COPY --from=build /app/Makefile /
COPY --from=build /app/.bot.env.deploy /bot.env
RUN apt-get update && apt-get install -y make ca-certificates

CMD ["make", "run"]
